# Language for plugin (es, en, de)
language: es

# Modelos de items para las tarjetas
yellowCardModel: "minecraft:yellow_banner"
redCardModel: "minecraft:red_banner"

# Configuraciones adicionales
maxYellowCards: 2
yellowCardCooldown: 3000
redCardCooldown: 3000
banDuration: 600000